#!/usr/bin/env Rscript
# tools/verify_refactor.R
# Codifies the acceptance checks used by every pipeline refactor in this repo.
#
# Two independent modes:
#   1. Byte-identity (default): run the default-mode pipeline refresh, then
#      classify every tracked file `git diff` reports as changed into expected
#      churn, known volatility, or genuine drift. Genuine drift fails the check.
#      This answers "does run N+1 byte-match run N?" (reproducibility).
#   2. --invariants: check a short list of cross-artifact consistency rules
#      against the current working tree, without running anything. This
#      answers "does artifact A agree with artifact B?" (consistency) — a
#      question byte-identity is structurally blind to, because a cache that
#      never regenerates trivially reproduces itself forever.
#
# Usage:
#   Rscript tools/verify_refactor.R              # runs the default 7-step refresh
#   Rscript tools/verify_refactor.R --full        # runs the --full 10-step refresh
#   Rscript tools/verify_refactor.R --skip-refresh # classifies the current working
#                                                   # tree without running anything
#   Rscript tools/verify_refactor.R --invariants   # runs only the cross-artifact
#                                                   # invariant checks (INV-001..013),
#                                                   # never the pipeline refresh
#
# Why git diff and not md5sum: git applies core.autocrlf normalization, so a
# byte-identical-after-normalization file shows as unchanged in `git diff`
# even when raw md5sum would differ across Windows/Linux line endings.
#
# PHASE-04 of plans/2026-07-20-wave0-orchestrator-sdb-closers-plan.md emptied
# this vector after deterministic run IDs were implemented in
# write_trisk_demo_outputs() (R/trisk_core.R). The five listed files no longer
# carry per-invocation UUIDs; any future diff in them is genuine drift.
VOLATILE_BASENAMES <- character(0)

# Wave 4 PHASE-01: normalize_report_html() / report_fingerprint() back the
# gated-HTML comparison below. Sourced from the repo root (the documented way
# to run this script) or from a test harness whose cwd is tests/testthat.
local({
  candidates <- c(
    "R/report_fingerprint.R",
    "../../R/report_fingerprint.R"
  )
  hit <- candidates[file.exists(candidates)]
  if (length(hit) > 0) source(hit[[1]])
})

# TIMESTAMP_BASENAMES: files whose only expected diff is generated-timestamp
# text or a run-scoped git_sha, never numeric content.
TIMESTAMP_BASENAMES <- c(
  "pipeline_manifest.json",
  "refresh_audit_metrics.json",
  "manifest.csv"
)

# A facts sidecar (.facts.json) changing is intentionally genuine drift: the
# numbers moved (Wave 5 PHASE-03). Sidecars carry no timestamp (ASM-005), so
# they cannot be timestamp-class.
# GATED_HTML_PATHS (Wave 4 PHASE-01): the HTML deliverables a pipeline run
# regenerates. Before this wave, classify_path() returned "timestamp-class" for
# EVERY .html file, so all 71 tracked HTML artifacts -- every client-facing
# report, the disclosure pack and the engagement letters index -- were outside
# the acceptance gate by construction. These paths are now compared after
# timestamp normalization (see R/report_fingerprint.R), so a changed number in
# a report is genuine drift.
#
# Deliberately EXCLUDED: the ~40 historical build reports under reports/ dated
# 2026-04 to 2026-08 (and their engagements/*/snapshot/ copies). They are
# static, never regenerated by any pipeline step, and gating them would compare
# a file nothing rewrites.
#
# Every path here must be TRACKED by git. The byte-identity gate classifies
# `git diff --name-only` output and compares against the HEAD blob, so an
# untracked file can never reach this list's code path. The engagement letters
# index and the disclosure pack are generated deliverables but are gitignored
# (.gitignore:21 and :23) -- they are covered by DISCLAIMER_HTML_PATHS below
# instead, which reads from disk and does not need a committed counterpart.
GATED_HTML_PATHS <- c(
  "reports/PACTA_Vietnam_Bank_Report.html",
  "reports/Financed_Emissions.html",
  "reports/SLL_Readiness_Shortlist.html",
  "reports/Sector_Target_Registry.html",
  "reports/BIDV_Framework_Recommendation_Report.html",
  "reports/pipeline_refresh_audit.html"
)

# DISCLAIMER_HTML_PATHS (Wave 4 PHASE-01, INV-010): every generated HTML
# deliverable that must carry the synthetic-data disclaimer, whether or not it
# is tracked by git. Superset of GATED_HTML_PATHS.
DISCLAIMER_HTML_PATHS <- c(
  GATED_HTML_PATHS,
  "output/disclosure/disclosure_pack.html",
  "output/engagement_letters/index.html"
)

#' Is a gated HTML file's working-tree content equal to its committed content
#' once generated timestamps, dates and git SHAs are normalized away?
#'
#' Compares against the HEAD blob rather than a stored digest, so the check has
#' no state to keep in sync. A path that does not exist at HEAD is a brand-new
#' report, which is an addition rather than drift.
#'
#' @param path character(1) — repo-relative path.
#' @param root character(1) — repo root.
#' @return logical(1) — TRUE when the only differences are timestamp-class.
.html_is_timestamp_only <- function(path, root = ".") {
  disk_path <- file.path(root, path)
  if (!file.exists(disk_path)) return(FALSE)

  # Capture `git show` into a file rather than via stdout = TRUE. These reports
  # embed base64 PNG payloads as single very long lines, and reading them
  # through an R pipe splits those lines at a buffer boundary -- which would
  # reinsert newlines mid-payload and make an untouched report read as drift.
  tmp <- tempfile("head_blob_")
  on.exit(unlink(tmp), add = TRUE)
  status <- tryCatch(
    suppressWarnings(system2(
      "git", args = c("-C", root, "show", paste0("HEAD:", path)),
      stdout = tmp, stderr = FALSE
    )),
    error = function(e) 1L
  )
  # Not in HEAD (new file), or git could not resolve the blob: an addition, not
  # drift.
  if (!identical(as.integer(status), 0L) || !file.exists(tmp)) return(TRUE)
  if (isTRUE(file.info(tmp)$size == 0)) return(TRUE)

  # Trailing-whitespace-trimmed so a missing/extra final newline -- an artifact
  # of how each side is written, not a real difference -- never reads as drift.
  disk_norm <- .trim_trailing(normalize_report_html(.read_utf8(disk_path)))
  head_norm <- .trim_trailing(normalize_report_html(.read_utf8(tmp)))
  identical(disk_norm, head_norm)
}

#' Drop trailing whitespace at the very end of a string.
#' @param x character(1).
#' @return character(1).
.trim_trailing <- function(x) sub("[ \t\r\n]+$", "", paste(x, collapse = "\n"))

#' Classify a single changed path into a drift bucket.
#' @param path character, a repo-relative path as reported by `git diff --name-only`.
#' @param volatile_basenames character vector of basenames known to carry only
#'   a regenerated run-id/run-path value between unmodified runs.
#' @param gated_html_paths character vector of repo-relative HTML deliverables
#'   compared by normalized content instead of being ignored.
#' @param root character, repo root used to resolve `path` and to run git.
#' @return character, one of "png-noise", "timestamp-class", "volatile", "drift".
classify_path <- function(path, volatile_basenames = VOLATILE_BASENAMES,
                          gated_html_paths = GATED_HTML_PATHS, root = ".") {
  ext <- tolower(tools::file_ext(path))
  base <- basename(path)
  if (identical(ext, "png")) {
    return("png-noise")
  }
  if (identical(ext, "html")) {
    # Wave 4 PHASE-01: a gated deliverable is compared, not assumed.
    if (gsub("\\\\", "/", path) %in% gated_html_paths) {
      return(if (.html_is_timestamp_only(path, root)) "timestamp-class" else "drift")
    }
    return("timestamp-class")
  }
  if (base %in% TIMESTAMP_BASENAMES) {
    return("timestamp-class")
  }
  if (base %in% volatile_basenames) {
    return("volatile")
  }
  # Wave 3 PHASE-04: history/ is append-only by construction
  # (R/run_history.R::record_run_history() refuses to overwrite an existing
  # run directory) -- every diff under it is a brand-new run being added,
  # never a modification of a prior one, so it is expected churn rather
  # than genuine drift.
  normalized <- gsub("\\\\", "/", path)
  if (identical(normalized, "history") || startsWith(normalized, "history/")) {
    return("timestamp-class")
  }
  "drift"
}

# ==============================================================================
# --invariants: cross-artifact consistency checks (INV-001..013)
#
# Each inv_*() function takes a repo root (and, where relevant, a snapshot
# directory) and returns list(id, ok, detail) — detail is a character vector
# of human-readable violation lines, empty when ok is TRUE.
# ==============================================================================

#' md5 digest of a file, or NA if the file does not exist.
#' @param path character — file path.
#' @return character(1) — lowercase md5 hex digest, or NA_character_.
.md5_of <- function(path) {
  if (!file.exists(path)) return(NA_character_)
  unname(tools::md5sum(path))
}

#' Extract a `c(...)` literal assigned to `var_name` from an R source file.
#' Used to check sector-list literals that are local variables (not exported
#' functions), so they cannot be read by sourcing + calling.
#'
#' Handles a literal that spans multiple lines (e.g. a long
#' `cran_packages <- c(\n  "a", "b",\n  "c"\n)` block): starting from the
#' matched line, it grows the candidate expression one line at a time until
#' it parses and evaluates successfully, up to 200 lines, so a single-line
#' literal (the common case elsewhere in this repo) still resolves on its
#' first attempt with no behavior change.
#' @param path character — R source file to scan.
#' @param var_name character — the variable name, e.g. "supported_sectors".
#' @return character vector of the literal's values, or NULL if the
#'   assignment could not be found or parsed.
.extract_c_literal_from_file <- function(path, var_name) {
  if (!file.exists(path)) return(NULL)
  lines <- readLines(path, warn = FALSE)
  pattern <- sprintf("^\\s*%s\\s*<-\\s*c\\(", var_name)
  idx <- grep(pattern, lines)
  if (length(idx) == 0) return(NULL)
  start <- idx[[1]]
  strip_pattern <- sprintf("^\\s*%s\\s*<-\\s*", var_name)

  max_end <- min(start + 199, length(lines))
  for (end in start:max_end) {
    expr_text <- sub(strip_pattern, "", paste(lines[start:end], collapse = "\n"))
    result <- tryCatch(eval(parse(text = expr_text)), error = function(e) NULL)
    if (!is.null(result)) return(result)
  }
  NULL
}

#' Sector set from R/sector_registry.R's sector_registry().
#' @param root character — repo root.
#' @return character vector of sectors, or NULL if the file could not be sourced.
.get_registry_sectors <- function(root) {
  env <- new.env()
  tryCatch({
    source(file.path(root, "R", "sector_registry.R"), local = env)
    sort(unique(env$sector_registry()$sector))
  }, error = function(e) NULL)
}

#' Sector set from R/trisk_core.R's trisk_supported_sectors constant.
#' @param root character — repo root.
#' @return character vector of sectors, or NULL if the file could not be sourced.
.get_trisk_supported_sectors <- function(root) {
  env <- new.env()
  tryCatch({
    source(file.path(root, "R", "trisk_core.R"), local = env)
    sort(unique(env$trisk_supported_sectors))
  }, error = function(e) NULL)
}

#' INV-001: the scenario grid's base-parameter cell must agree with the base
#' (non-grid) TRISK run for every sector marked grid_available in the
#' published manifest. Catches a grid cache that has gone stale relative to
#' its own base run.
#' @param root character — repo root.
#' @param snapshot_dir character — snapshot directory relative to root,
#'   default "dashboard/data".
#' @param tolerance numeric — max allowed |grid - base| per metric, default 1e-6.
#' @return list(id = "INV-001", ok, detail).
inv_grid_matches_base_run <- function(root, snapshot_dir = "dashboard/data", tolerance = 1e-2) {
  manifest_path <- file.path(root, snapshot_dir, "trisk", "manifest.csv")
  detail <- character(0)
  if (!file.exists(manifest_path)) {
    return(list(id = "INV-001", ok = TRUE, detail = detail))
  }

  manifest <- utils::read.csv(manifest_path, stringsAsFactors = FALSE)
  sectors <- manifest$sector[manifest$grid_available == TRUE]

  # Mirrors build_scenario_id() in R/trisk_core.R for trisk_base_params():
  # shock_year=2028, discount_rate=0.08, risk_free_rate=0.03,
  # market_passthrough=0.25, carbon_price_family="NGFS_NetZero2050".
  base_scenario_id <- "s2028_d0.08_rf0.03_mp0.25_cNGFS_NetZero2050"

  for (sector in sectors) {
    grid_path <- file.path(root, snapshot_dir, "trisk", "grid", sector, "borrower_results.parquet")
    summary_path <- file.path(root, snapshot_dir, "trisk", sector, "company_summary.csv")
    if (!file.exists(grid_path) || !file.exists(summary_path)) {
      next
    }

    grid <- as.data.frame(arrow::read_parquet(grid_path))
    grid_base <- grid[grid$scenario_id == base_scenario_id, c("company_id", "npv_change_pct", "pd_change_pct"), drop = FALSE]

    summary <- utils::read.csv(summary_path, stringsAsFactors = FALSE)
    summary_base <- summary[, c("company_id", "npv_change", "pd_change"), drop = FALSE]

    grid_ids <- sort(unique(grid_base$company_id))
    summary_ids <- sort(unique(summary_base$company_id))

    only_in_summary <- setdiff(summary_ids, grid_ids)
    only_in_grid <- setdiff(grid_ids, summary_ids)
    if (length(only_in_summary) > 0 || length(only_in_grid) > 0) {
      detail <- c(detail, sprintf(
        "%s: company_id sets differ%s%s",
        sector,
        if (length(only_in_summary) > 0) sprintf(" — missing from grid: %s", paste(only_in_summary, collapse = ", ")) else "",
        if (length(only_in_grid) > 0) sprintf(" — missing from base run: %s", paste(only_in_grid, collapse = ", ")) else ""
      ))
    }

    common_ids <- intersect(grid_ids, summary_ids)
    for (cid in common_ids) {
      g <- grid_base[grid_base$company_id == cid, , drop = FALSE][1, ]
      s <- summary_base[summary_base$company_id == cid, , drop = FALSE][1, ]
      npv_diff <- abs(g$npv_change_pct - s$npv_change)
      pd_diff <- abs(g$pd_change_pct - s$pd_change)
      if (!is.na(npv_diff) && npv_diff > tolerance) {
        detail <- c(detail, sprintf(
          "%s/%s: grid npv_change_pct=%.6f vs base npv_change=%.6f (delta %.6f)",
          sector, cid, g$npv_change_pct, s$npv_change, npv_diff
        ))
      }
      if (!is.na(pd_diff) && pd_diff > tolerance) {
        detail <- c(detail, sprintf(
          "%s/%s: grid pd_change_pct=%.6f vs base pd_change=%.6f (delta %.6f)",
          sector, cid, g$pd_change_pct, s$pd_change, pd_diff
        ))
      }
    }
  }

  list(id = "INV-001", ok = length(detail) == 0, detail = detail)
}

#' INV-002: every file under data/scenarios/<vintage>/ must be the only copy
#' of its content — no byte-identical twin directly under data/. Catches
#' "versioning" that duplicated rather than moved a file.
#' @param root character — repo root.
#' @return list(id = "INV-002", ok, detail).
inv_scenario_vintage_single_source <- function(root) {
  scenarios_dir <- file.path(root, "data", "scenarios")
  detail <- character(0)
  if (!dir.exists(scenarios_dir)) {
    return(list(id = "INV-002", ok = TRUE, detail = detail))
  }

  vintage_files <- list.files(scenarios_dir, recursive = TRUE, full.names = TRUE)
  for (vf in vintage_files) {
    flat_path <- file.path(root, "data", basename(vf))
    if (!file.exists(flat_path)) next
    h_vintage <- .md5_of(vf)
    h_flat <- .md5_of(flat_path)
    if (!is.na(h_vintage) && !is.na(h_flat) && identical(h_vintage, h_flat)) {
      detail <- c(detail, sprintf("%s == %s (md5 %s)", flat_path, vf, h_vintage))
    }
  }

  list(id = "INV-002", ok = length(detail) == 0, detail = detail)
}

#' INV-003: every committed per-engagement CSV that carries a `data_source`
#' column must name its own bank_slug, never another engagement's. Catches
#' hardcoded provenance leaking into a client deliverable.
#'
#' Wave 4 PHASE-03 widened this from `engagement_priority.csv` alone to every
#' per-engagement output. Wave 3 added three more such CSVs and none inherited
#' the guard, which is why `R/financed_emissions.R` could hardcode
#' `data_source = "mcb-demo"` and stamp it on Saigon Delta Bank's committed
#' financed-emissions inventory without any gate objecting.
#'
#' @param root character — repo root.
#' @return list(id = "INV-003", ok, detail).
inv_engagement_data_source <- function(root) {
  detail <- character(0)
  config_paths <- Sys.glob(file.path(root, "engagements", "*", "engagement_config.json"))

  for (config_path in config_paths) {
    cfg <- tryCatch(jsonlite::fromJSON(config_path, simplifyVector = TRUE), error = function(e) NULL)
    if (is.null(cfg) || is.null(cfg$bank_slug) || is.null(cfg$paths)) next

    candidates <- character(0)
    if (!is.null(cfg$paths$engagement_output_dir)) {
      candidates <- c(candidates, file.path(
        root, cfg$paths$engagement_output_dir,
        c("engagement_priority.csv", "sll_readiness.csv", "target_registry.csv")
      ))
    }
    if (!is.null(cfg$paths$financed_emissions_output_dir)) {
      candidates <- c(candidates, file.path(
        root, cfg$paths$financed_emissions_output_dir, "financed_emissions.csv"
      ))
    }

    for (csv_path in candidates) {
      if (!file.exists(csv_path)) next
      df <- tryCatch(utils::read.csv(csv_path, stringsAsFactors = FALSE), error = function(e) NULL)
      if (is.null(df) || !"data_source" %in% names(df) || nrow(df) == 0) next

      present <- df$data_source[!is.na(df$data_source) & nzchar(df$data_source)]
      bad_values <- unique(present[present != cfg$bank_slug])
      if (length(bad_values) > 0) {
        detail <- c(detail, sprintf(
          "%s: expected data_source '%s', found '%s'",
          csv_path, cfg$bank_slug, paste(bad_values, collapse = "', '")
        ))
      }
    }
  }

  list(id = "INV-003", ok = length(detail) == 0, detail = detail)
}

#' INV-004: the supported-sector list must agree across every place it is
#' hardcoded (R/sector_registry.R, R/engagement_config.R, R/trisk_core.R,
#' scripts/new_engagement.R). Catches drift when a sector is added in one
#' place and not the others.
#' @param root character — repo root.
#' @return list(id = "INV-004", ok, detail).
#' Locate hardcoded `c("power", "cement", "steel")` literals outside the small
#' set of files entitled to declare the supported-sector list.
#'
#' Wave 4 PHASE-03. INV-004 previously compared four hand-registered sites, so
#' it could only catch drift among places someone remembered to register --
#' and Wave 3 duly added two it did not know about (`R/target_setting.R` and
#' `scripts/generate_financed_emissions.R`). Scanning for the literal instead
#' makes the invariant self-maintaining.
#'
#' @param root character — repo root.
#' @param allowlist character — repo-relative files entitled to the literal.
#' @return character — "path:line" for each unentitled occurrence.
.scan_hardcoded_sector_triples <- function(root,
                                           allowlist = c(
                                             "R/sector_registry.R",
                                             "R/engagement_config.R",
                                             "R/trisk_core.R",
                                             "scripts/new_engagement.R"
                                           )) {
  pattern <- '"power"\\s*,\\s*"cement"\\s*,\\s*"steel"'
  hits <- character(0)
  dirs <- file.path(root, c("R", "scripts", "tools"))
  files <- unlist(lapply(dirs[dir.exists(dirs)], function(d) {
    list.files(d, pattern = "\\.R$", full.names = TRUE, recursive = TRUE)
  }), use.names = FALSE)

  for (f in files) {
    rel <- gsub("\\\\", "/", sub(paste0("^", gsub("\\\\", "/", normalizePath(root, winslash = "/")), "/?"),
                                "", gsub("\\\\", "/", normalizePath(f, winslash = "/"))))
    if (rel %in% allowlist) next
    lines <- tryCatch(readLines(f, warn = FALSE), error = function(e) character(0))
    # Ignore comment lines: prose may legitimately mention the three sectors.
    idx <- grep(pattern, lines)
    idx <- idx[!grepl("^\\s*#", lines[idx])]
    if (length(idx) > 0) hits <- c(hits, sprintf("%s:%d", rel, idx))
  }
  hits
}

inv_sector_lists_agree <- function(root) {
  sources <- list(
    sector_registry = .get_registry_sectors(root),
    engagement_config = .extract_c_literal_from_file(file.path(root, "R", "engagement_config.R"), "supported_sectors"),
    trisk_core = .get_trisk_supported_sectors(root),
    new_engagement = .extract_c_literal_from_file(file.path(root, "scripts", "new_engagement.R"), "supported")
  )

  detail <- character(0)

  # Self-maintaining half: any sector triple outside the entitled files.
  stray <- .scan_hardcoded_sector_triples(root)
  if (length(stray) > 0) {
    detail <- c(detail, sprintf(
      "hardcoded sector list outside the registry at %s (use sector_registry()$sector)",
      stray
    ))
  }
  failed <- character(0)
  for (name in names(sources)) {
    if (is.null(sources[[name]])) {
      detail <- c(detail, sprintf("%s: literal could not be located/parsed", name))
      failed <- c(failed, name)
    }
  }
  if (length(failed) > 0) {
    return(list(id = "INV-004", ok = FALSE, detail = detail))
  }

  normalized <- lapply(sources, function(s) sort(unique(s)))
  ref <- normalized[[1]]
  all_equal <- all(vapply(normalized, function(s) identical(s, ref), logical(1)))
  if (!all_equal) {
    for (name in names(normalized)) {
      detail <- c(detail, sprintf("%s: %s", name, paste(normalized[[name]], collapse = ", ")))
    }
    return(list(id = "INV-004", ok = FALSE, detail = detail))
  }

  # `detail` may already hold stray-literal findings from the scan above, so
  # the verdict is "no findings", not an unconditional TRUE.
  list(id = "INV-004", ok = length(detail) == 0, detail = detail)
}

#' INV-005: every sector named in the published TRISK manifest must be a
#' known sector in sector_registry(). Catches a snapshot advertising a sector
#' the registry no longer knows about.
#' @param root character — repo root.
#' @param snapshot_dir character — snapshot directory relative to root,
#'   default "dashboard/data".
#' @return list(id = "INV-005", ok, detail).
inv_snapshot_manifest_sectors <- function(root, snapshot_dir = "dashboard/data") {
  manifest_path <- file.path(root, snapshot_dir, "trisk", "manifest.csv")
  if (!file.exists(manifest_path)) {
    return(list(id = "INV-005", ok = TRUE, detail = character(0)))
  }

  registry_sectors <- .get_registry_sectors(root)
  if (is.null(registry_sectors)) {
    return(list(id = "INV-005", ok = FALSE, detail = "sector_registry() could not be loaded"))
  }

  manifest <- utils::read.csv(manifest_path, stringsAsFactors = FALSE)
  missing <- setdiff(manifest$sector, registry_sectors)
  if (length(missing) > 0) {
    detail <- sprintf("manifest sector '%s' not in sector_registry()", missing)
    return(list(id = "INV-005", ok = FALSE, detail = detail))
  }

  list(id = "INV-005", ok = TRUE, detail = character(0))
}

#' INV-006: every engagement's declared-VND loanbook must have a plausible
#' magnitude for whole VND, not thousands or millions of VND. Catches a data
#' generator that forgot to apply its own currency's scale (Wave 2 PHASE-02,
#' U1) — a corporate loan denominated in true VND is never a few hundred
#' thousand units, but a loanbook denominated in millions-of-VND while
#' labeled "VND" produces exactly that.
#' @param root character — repo root.
#' @param threshold numeric — minimum plausible median
#'   `loan_size_outstanding` for a VND-denominated loanbook, default 1e8
#'   (100 million VND, roughly USD 3,800 — comfortably below any real
#'   corporate loan floor but far above the 1e5-1e6 range a
#'   millions-denominated book produces).
#' @return list(id = "INV-006", ok, detail).
inv_loanbook_currency_scale <- function(root, threshold = 1e8) {
  detail <- character(0)
  config_paths <- Sys.glob(file.path(root, "engagements", "*", "engagement_config.json"))

  for (config_path in config_paths) {
    cfg <- tryCatch(jsonlite::fromJSON(config_path, simplifyVector = TRUE), error = function(e) NULL)
    if (is.null(cfg) || is.null(cfg$inputs) || length(cfg$inputs$loanbook_csv) == 0) {
      next
    }
    loanbook_path <- file.path(root, cfg$inputs$loanbook_csv)
    if (!file.exists(loanbook_path)) next

    lb <- tryCatch(utils::read.csv(loanbook_path, stringsAsFactors = FALSE), error = function(e) NULL)
    if (is.null(lb) || !all(c("loan_size_outstanding", "loan_size_outstanding_currency") %in% names(lb))) {
      next
    }

    vnd_rows <- lb[lb$loan_size_outstanding_currency == "VND", , drop = FALSE]
    if (nrow(vnd_rows) == 0) next

    med <- stats::median(vnd_rows$loan_size_outstanding, na.rm = TRUE)
    if (!is.na(med) && med < threshold) {
      detail <- c(detail, sprintf(
        "%s: median VND-currency loan_size_outstanding = %s, below plausible threshold %s",
        config_path,
        format(med, big.mark = ",", scientific = FALSE),
        format(threshold, big.mark = ",", scientific = FALSE)
      ))
    }
  }

  list(id = "INV-006", ok = length(detail) == 0, detail = detail)
}

#' INV-007: no file tracked by git under engagements/<slug>/ may belong to a
#' slug outside an explicit fixture allowlist, except the slug's own
#' engagement_config.json. Wave 3 PHASE-01: the .gitignore negations that keep
#' the sdb-rehearsal regression fixtures tracked were wildcards over every
#' slug (`!engagements/*/intake/normalized_loanbook.csv`, etc.) — a real
#' client engagement's normalized loanbook or engagement_priority.csv would
#' have been staged by a plain `git add -A`, in direct contradiction of
#' docs/intake_privacy.md rule 1 ("No raw client data is committed to git").
#' This invariant is the mechanical backstop for that fix: even if a future
#' .gitignore edit reintroduces a wildcard negation, a committed file for an
#' unlisted slug fails the build rather than silently landing.
#' @param root character — repo root.
#' @param allowlist character — engagement slugs permitted to carry tracked
#'   fixture files beyond their own engagement_config.json, default
#'   c("sdb-rehearsal").
#' @return list(id = "INV-007", ok, detail).
inv_engagement_fixture_allowlist <- function(root, allowlist = c("sdb-rehearsal")) {
  detail <- character(0)
  tracked <- tryCatch(
    system2("git", args = c("-C", root, "ls-files", "engagements"), stdout = TRUE),
    error = function(e) character(0)
  )
  tracked <- tracked[nzchar(tracked)]

  for (path in tracked) {
    parts <- strsplit(path, "/", fixed = TRUE)[[1]]
    if (length(parts) < 2) next
    slug <- parts[2]
    is_own_config <- length(parts) == 3 && identical(parts[3], "engagement_config.json")
    if (is_own_config) next
    if (!(slug %in% allowlist)) {
      detail <- c(detail, sprintf(
        "tracked path '%s' belongs to slug '%s', which is not in the fixture allowlist (%s)",
        path, slug, paste(allowlist, collapse = ", ")
      ))
    }
  }

  list(id = "INV-007", ok = length(detail) == 0, detail = detail)
}

#' Parse a comma-separated DESCRIPTION field (e.g. "Imports" or "Suggests")
#' into a clean vector of bare package names, stripping any version
#' constraint (e.g. "dplyr (>= 1.1.0)" -> "dplyr").
#' @param root character — repo root.
#' @param field character(1) — the DCF field name to read.
#' @return character vector of package names, or character(0) if the field
#'   is absent.
.parse_description_field <- function(root, field) {
  desc_path <- file.path(root, "DESCRIPTION")
  if (!file.exists(desc_path)) return(character(0))
  raw <- tryCatch(read.dcf(desc_path, fields = field)[1, 1], error = function(e) NA_character_)
  if (is.na(raw)) return(character(0))
  parts <- strsplit(raw, ",")[[1]]
  parts <- trimws(gsub("\\s*\\([^)]*\\)", "", parts))
  parts <- parts[nzchar(parts)]
  parts
}

#' Package names scripts/ci/install_deps.R installs: the cran_packages
#' literal plus trisk.model IF the file separately installs it from a pinned
#' GitHub tarball (not CRAN, so it is never part of the c(...) literal) --
#' detected by a literal "trisk.model" string appearing anywhere else in the
#' file, so a fixture install_deps.R that genuinely does not install it is
#' not falsely credited with doing so.
#' @param root character — repo root.
#' @return character vector of package names, or character(0) if the file
#'   or its cran_packages literal could not be found/parsed.
.parse_install_deps_packages <- function(root) {
  path <- file.path(root, "scripts", "ci", "install_deps.R")
  cran <- .extract_c_literal_from_file(path, "cran_packages")
  if (is.null(cran)) return(character(0))
  dev <- .extract_c_literal_from_file(path, "dev_packages")
  if (!is.null(dev)) cran <- union(cran, dev)
  if (any(grepl("trisk.model", readLines(path, warn = FALSE), fixed = TRUE))) {
    return(union(cran, "trisk.model"))
  }
  cran
}

#' Package names recorded in renv.lock's Packages block.
#' @param root character — repo root.
#' @return character vector of package names, or character(0) if renv.lock
#'   is absent or unparseable.
.parse_renv_lock_packages <- function(root) {
  path <- file.path(root, "renv.lock")
  if (!file.exists(path)) return(character(0))
  lock <- tryCatch(jsonlite::fromJSON(path, simplifyVector = TRUE), error = function(e) NULL)
  if (is.null(lock) || is.null(lock$Packages)) return(character(0))
  names(lock$Packages)
}

#' INV-008: DESCRIPTION's Imports must be a superset of every package
#' scripts/ci/install_deps.R installs and every package renv.lock records
#' (Suggests-listed dev tooling is exempt). Wave 3 PHASE-02 (F-007): before
#' this invariant, trisk.model -- the single most load-bearing dependency in
#' the repository -- was absent from DESCRIPTION entirely, undetected because
#' CI's "package loads" check uses devtools::load_all(), which does not
#' consult Imports.
#' @param root character — repo root.
#' @return list(id = "INV-008", ok, detail).
inv_dependency_manifests_agree <- function(root) {
  imports <- .parse_description_field(root, "Imports")
  suggests <- .parse_description_field(root, "Suggests")
  install_deps_pkgs <- .parse_install_deps_packages(root)
  renv_pkgs <- .parse_renv_lock_packages(root)

  declared <- union(imports, suggests)
  all_used <- union(install_deps_pkgs, renv_pkgs)
  missing <- setdiff(all_used, declared)
  # A package declared only in Suggests is exempt from the "must be in
  # Imports" requirement but must not be reported missing.
  missing <- setdiff(missing, suggests)

  detail <- character(0)
  if (length(missing) > 0) {
    sources <- vapply(missing, function(pkg) {
      in_install <- pkg %in% install_deps_pkgs
      in_renv <- pkg %in% renv_pkgs
      paste(c(
        if (in_install) "scripts/ci/install_deps.R",
        if (in_renv) "renv.lock"
      ), collapse = ", ")
    }, character(1))
    detail <- sprintf(
      "'%s' is used by (%s) but missing from DESCRIPTION Imports",
      missing, sources
    )
  }

  list(id = "INV-008", ok = length(detail) == 0, detail = detail)
}

#' INV-009: every engagement's declared inputs.scenario_vintage must equal
#' the parent directory of both its scenario CSV paths, and that vintage
#' directory must actually exist. This is the acceptance-gate twin of the
#' same check R/engagement_config.R performs at load time (Wave 3 PHASE-03)
#' — it catches a config file hand-edited or generated outside
#' load_engagement_config() (e.g. a committed engagement_config.resolved.json)
#' that was never actually validated.
#' @param root character — repo root.
#' @return list(id = "INV-009", ok, detail).
inv_scenario_vintage_declared <- function(root) {
  detail <- character(0)
  config_paths <- Sys.glob(file.path(root, "engagements", "*", "engagement_config.json"))

  for (config_path in config_paths) {
    cfg <- tryCatch(jsonlite::fromJSON(config_path, simplifyVector = TRUE), error = function(e) NULL)
    if (is.null(cfg) || is.null(cfg$inputs)) next

    vintage <- cfg$inputs$scenario_vintage
    ms_csv <- cfg$inputs$scenario_ms_csv
    co2_csv <- cfg$inputs$scenario_co2_csv
    if (length(vintage) == 0 || length(ms_csv) == 0 || length(co2_csv) == 0) next

    ms_dir <- basename(dirname(ms_csv))
    co2_dir <- basename(dirname(co2_csv))
    if (!identical(ms_dir, vintage) || !identical(co2_dir, vintage)) {
      detail <- c(detail, sprintf(
        "%s: inputs.scenario_vintage ('%s') does not match the parent directory of scenario_ms_csv ('%s') and/or scenario_co2_csv ('%s')",
        config_path, vintage, ms_csv, co2_csv
      ))
      next
    }

    vintage_dir <- file.path(root, "data", "scenarios", vintage)
    if (!dir.exists(vintage_dir)) {
      detail <- c(detail, sprintf(
        "%s: declared scenario_vintage '%s' has no directory at %s",
        config_path, vintage, vintage_dir
      ))
    }
  }

  list(id = "INV-009", ok = length(detail) == 0, detail = detail)
}

#' INV-010: every gated HTML deliverable that exists must carry the
#' synthetic-data disclaimer.
#'
#' CLAUDE.md makes this non-negotiable ("Synthetic-data disclaimers ... must
#' always state the data is synthetic/illustrative"), but until Wave 4 nothing
#' checked it -- the repo's most load-bearing legal guarantee was enforced by
#' discipline while its numeric outputs had three layers of automated gates.
#' A file that does not exist is skipped, not failed: an engagement may not
#' have run the step that produces it.
#'
#' @param root character — repo root.
#' @param html_paths character — deliverables to check (tracked or not).
#' @return list(id = "INV-010", ok, detail).
inv_deliverables_carry_disclaimer <- function(root, html_paths = DISCLAIMER_HTML_PATHS) {
  detail <- character(0)
  for (rel in html_paths) {
    path <- file.path(root, rel)
    if (!file.exists(path)) next
    txt <- tryCatch(.read_utf8(path), error = function(e) NA_character_)
    if (is.na(txt)) {
      detail <- c(detail, sprintf("%s: could not be read", rel))
      next
    }
    if (!grepl("synthetic", txt, ignore.case = TRUE)) {
      detail <- c(detail, sprintf("%s: no synthetic-data disclaimer found", rel))
    }
  }
  list(id = "INV-010", ok = length(detail) == 0, detail = detail)
}

#' Every engagement's manifest path, keyed by config path.
#' @param root character — repo root.
#' @return named list of list(cfg, manifest_path).
.engagement_manifests <- function(root) {
  out <- list()
  for (config_path in Sys.glob(file.path(root, "engagements", "*", "engagement_config.json"))) {
    cfg <- tryCatch(jsonlite::fromJSON(config_path, simplifyVector = TRUE), error = function(e) NULL)
    if (is.null(cfg) || is.null(cfg$bank_slug)) next
    manifest_path <- if (isTRUE(cfg$public_snapshot_allowed) && !is.null(cfg$paths$snapshot_dir)) {
      file.path(root, cfg$paths$snapshot_dir, "pipeline_manifest.json")
    } else {
      file.path(root, "engagements", cfg$bank_slug, "pipeline_manifest.json")
    }
    out[[config_path]] <- list(cfg = cfg, manifest_path = manifest_path)
  }
  out
}

#' INV-011: a complete pipeline manifest must not report an identical
#' wall-clock duration for every one of its steps.
#'
#' A genuine multi-step run of this pipeline cannot produce the same `seconds`
#' value for PACTA, three TRISK sector runs and the scenario grid -- the
#' committed MCB manifest that motivated this check reported "seconds": 1 for
#' all 16 steps while the SDB manifest reported 2.3 to 28.8 for the same work.
#' Deliberately weak: it asserts no specific timing (which would be
#' machine-dependent), only that a complete run's timings are not degenerate.
#' A `partial` run is exempt, and fewer than 3 steps is not enough evidence.
#'
#' @param root character — repo root.
#' @return list(id = "INV-011", ok, detail).
inv_manifest_plausible <- function(root) {
  detail <- character(0)
  for (entry in .engagement_manifests(root)) {
    mp <- entry$manifest_path
    if (!file.exists(mp)) next
    m <- tryCatch(jsonlite::fromJSON(mp, simplifyVector = TRUE), error = function(e) NULL)
    if (is.null(m) || is.null(m$steps)) next
    if (isTRUE(m$partial)) next

    seconds <- tryCatch(as.numeric(m$steps$seconds), error = function(e) numeric(0))
    seconds <- seconds[!is.na(seconds)]
    if (length(seconds) < 3) next
    if (length(unique(seconds)) == 1) {
      detail <- c(detail, sprintf(
        "%s: all %d steps report the same duration (%s s) and the run is not marked partial",
        mp, length(seconds), format(seconds[[1]])
      ))
    }
  }
  list(id = "INV-011", ok = length(detail) == 0, detail = detail)
}

#' INV-012: the refresh audit's recorded scenario checksums must match the
#' scenario files the engagement's config actually declares.
#'
#' scripts/generate_refresh_audit.R hardcoded `data/scenarios/pdp8-2023/` until
#' Wave 4, so after Wave 3 moved mcb-demo to `pdp8-2025-adjusted` the audit
#' published the digests of files the pipeline never read. INV-009 checks only
#' that a vintage is DECLARED; this checks that the artifacts ATTEST to it.
#'
#' @param root character — repo root.
#' @return list(id = "INV-012", ok, detail).
inv_audit_attests_configured_vintage <- function(root) {
  detail <- character(0)
  for (entry in .engagement_manifests(root)) {
    cfg <- entry$cfg
    if (!isTRUE(cfg$public_snapshot_allowed)) next
    if (is.null(cfg$paths$reports_dir)) next

    metrics_path <- file.path(root, cfg$paths$reports_dir, "refresh_audit_metrics.json")
    if (!file.exists(metrics_path)) next
    metrics <- tryCatch(jsonlite::fromJSON(metrics_path, simplifyVector = TRUE), error = function(e) NULL)
    if (is.null(metrics)) next

    checks <- list(
      list(field = "scenario_ms_checksum", path = cfg$inputs$scenario_ms_csv),
      list(field = "scenario_co2_checksum", path = cfg$inputs$scenario_co2_csv)
    )
    for (chk in checks) {
      recorded <- metrics[[chk$field]]
      if (is.null(recorded) || length(recorded) == 0 || is.na(recorded)) next
      if (is.null(chk$path) || length(chk$path) == 0) next
      computed <- .md5_of(file.path(root, chk$path))
      if (is.na(computed)) {
        detail <- c(detail, sprintf(
          "%s: %s declares %s, which does not exist",
          metrics_path, chk$field, chk$path
        ))
      } else if (!identical(as.character(recorded), computed)) {
        detail <- c(detail, sprintf(
          "%s: %s is %s but the configured input %s hashes to %s",
          metrics_path, chk$field, recorded, chk$path, computed
        ))
      }
    }
  }
  list(id = "INV-012", ok = length(detail) == 0, detail = detail)
}

#' INV-013: every gated report's facts sidecar must agree with its source
#' CSVs and its rendered HTML (Wave 5 PHASE-03 -- the fact-assertion half of
#' Wave 4's DEC-001). For every path p in the gated list, let s be p with
#' `.html` replaced by `.facts.json`. A report without a sidecar is skipped
#' (not yet covered); a sidecar whose values do not recompute from their
#' source CSVs, or whose rendered strings do not appear in the HTML, is a
#' violation.
#'
#' @param root character -- repo root.
#' @param gated_html_paths character -- override for tests; default
#'   GATED_HTML_PATHS.
#' @return list(id = "INV-013", ok, detail).
inv_report_facts_agree <- function(root, gated_html_paths = GATED_HTML_PATHS) {
  detail <- character(0)
  for (p in gated_html_paths) {
    s_path <- sub("\\.html$", ".facts.json", p)
    sidecar <- file.path(root, s_path)
    if (!file.exists(sidecar)) next
    disk <- file.path(root, p)
    if (!file.exists(disk)) {
      detail <- c(detail, sprintf("%s has a facts sidecar but no report", p))
      next
    }
    parsed <- tryCatch(
      jsonlite::fromJSON(sidecar, simplifyVector = FALSE),
      error = function(e) NULL
    )
    if (is.null(parsed) || is.null(parsed$facts)) {
      detail <- c(detail, sprintf("%s: facts sidecar is missing a facts array", p))
      next
    }
    html <- paste(readLines(disk, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
    for (fact in parsed$facts) {
      name <- fact$name
      value <- suppressWarnings(as.numeric(fact$value))
      csv_rel <- fact$source$csv
      column <- fact$source$column
      agg <- fact$source$agg
      rendered <- fact$rendered
      csv_path <- file.path(root, csv_rel)
      if (!file.exists(csv_path)) {
        detail <- c(detail, sprintf("%s: fact '%s' source CSV is missing: %s", p, name, csv_rel))
        next
      }
      df <- tryCatch(utils::read.csv(csv_path, stringsAsFactors = FALSE),
                     error = function(e) NULL)
      if (is.null(df)) {
        detail <- c(detail, sprintf("%s: fact '%s' source CSV is unreadable: %s", p, name, csv_rel))
        next
      }
      recomputed <- NA_real_
      if (identical(agg, "sum")) {
        recomputed <- sum(as.numeric(df[[column]]), na.rm = TRUE)
      } else if (identical(agg, "nrow")) {
        recomputed <- nrow(df)
      } else if (identical(agg, "n_distinct")) {
        recomputed <- length(unique(df[[column]]))
      } else {
        detail <- c(detail, sprintf("%s: fact '%s' has unknown agg '%s'", p, name, agg))
        next
      }
      if (is.na(value) || is.na(recomputed) ||
          abs(recomputed - value) > 1e-9 * max(1, abs(value))) {
        detail <- c(detail, sprintf(
          "%s: fact '%s' is %s but %s gives %s",
          p, name, as.character(fact$value), csv_rel, as.character(recomputed)
        ))
      }
      if (is.null(rendered) || length(rendered) == 0 ||
          !grepl(rendered, html, fixed = TRUE)) {
        detail <- c(detail, sprintf(
          "%s: fact '%s' rendered as '%s' does not appear in the report",
          p, name, as.character(rendered)
        ))
      }
    }
  }
  list(id = "INV-013", ok = length(detail) == 0, detail = detail)
}

#' Run every cross-artifact invariant and print a [PASS]/[FAIL] report.
#' @param root character — repo root.
#' @param snapshot_dir character — snapshot directory relative to root,
#'   default "dashboard/data".
#' @return logical(1) — TRUE iff every invariant passed.
run_invariants <- function(root, snapshot_dir = "dashboard/data") {
  results <- list(
    inv_grid_matches_base_run(root, snapshot_dir),
    inv_scenario_vintage_single_source(root),
    inv_engagement_data_source(root),
    inv_sector_lists_agree(root),
    inv_snapshot_manifest_sectors(root, snapshot_dir),
    inv_loanbook_currency_scale(root),
    inv_engagement_fixture_allowlist(root),
    inv_dependency_manifests_agree(root),
    inv_scenario_vintage_declared(root),
    inv_deliverables_carry_disclaimer(root),
    inv_manifest_plausible(root),
    inv_audit_attests_configured_vintage(root),
    inv_report_facts_agree(root)
  )

  for (r in results) {
    cat(sprintf("[%s] %s\n", if (isTRUE(r$ok)) "PASS" else "FAIL", r$id))
    if (!isTRUE(r$ok) && length(r$detail) > 0) {
      for (d in r$detail) cat(sprintf("    %s\n", d))
    }
  }

  all(vapply(results, function(r) isTRUE(r$ok), logical(1)))
}

run_refresh <- function(full_mode) {
  cat(sprintf("=== Running pipeline_refresh.R%s ===\n", if (full_mode) " --full" else ""))
  status <- system2("Rscript", args = c("scripts/pipeline_refresh.R", if (full_mode) "--full"))
  if (status != 0) {
    cat("[FAIL] scripts/pipeline_refresh.R exited non-zero; aborting verification.\n")
    quit(status = 1)
  }
}

changed_paths <- function() {
  out <- system2("git", args = c("diff", "--name-only"), stdout = TRUE)
  out[nzchar(out)]
}

main <- function() {
  args <- commandArgs(trailingOnly = TRUE)
  full_mode <- "--full" %in% args
  skip_refresh <- "--skip-refresh" %in% args
  invariants_mode <- "--invariants" %in% args

  if (invariants_mode) {
    ok <- run_invariants(getwd())
    if (ok) {
      cat("\nINVARIANTS PASS\n")
      quit(status = 0)
    } else {
      cat("\nINVARIANTS FAIL\n")
      quit(status = 1)
    }
  }

  if (!skip_refresh) {
    run_refresh(full_mode)
  } else {
    cat("=== --skip-refresh: classifying current working tree only ===\n")
  }

  paths <- changed_paths()
  if (length(paths) == 0) {
    cat("\nNo tracked files changed.\nBYTE-IDENTITY PASS\n")
    quit(status = 0)
  }

  classes <- vapply(paths, classify_path, character(1), volatile_basenames = VOLATILE_BASENAMES)

  print_section <- function(label, class_name) {
    hits <- paths[classes == class_name]
    if (length(hits) == 0) return(invisible())
    cat(sprintf("\n--- %s (%d) ---\n", label, length(hits)))
    for (p in hits) cat(sprintf("  %s\n", p))
  }

  print_section("png-noise (ignored)", "png-noise")
  print_section("expected churn: timestamps / manifests (ignored)", "timestamp-class")
  print_section("known-volatile: run_id/run_path noise (ignored; retire in PHASE-04)", "volatile")
  print_section("DRIFT", "drift")

  n_drift <- sum(classes == "drift")
  if (n_drift > 0) {
    cat(sprintf("\nDRIFT DETECTED (%d files)\n", n_drift))
    quit(status = 1)
  }

  cat("\nBYTE-IDENTITY PASS\n")
  quit(status = 0)
}

if (identical(environment(), globalenv()) && sys.nframe() == 0L) {
  main()
}
